cloud-native-toolkit/terraform-ocp-login

- .github/workflows/verify.yaml
- main.tf
- module.yaml
- scripts/oc-login.sh
- variables.tf
- version.tf
> Moves password and token to env variables so they aren't printed

- test/stages/stage-cluster.tf
- variables.tf
> Removes default values from server_url and login_token

- .github/workflows/publish-assets.yaml
- .github/workflows/verify.yaml
-Adds metadata validation to workflow
> Updates action-module-catalog to v2 to handle sensitive flag

- outputs.tf
> Adds name, region, and resource_group_name outputs to follow interface

- .github/workflows/publish-assets.yaml
- .github/workflows/verify.yaml
- outputs.tf
Consolidates logic into cloud-native-toolkit/action-module-metadata-create action
> Updates workflow to use new action

- main.tf
- outputs.tf
- scripts/oc-login.sh
> Updates oc-login to use external data source

- .github/scripts/validate-deploy.sh
- main.tf
- outputs.tf
- test/stages/stage-cluster.tf
> Updates validate deploy logic

- .github/scripts/validate-deploy.sh
- .github/workflows/verify.yaml
- main.tf
- scripts/oc-login.sh
- test/stages/stage0.tf
> Updates test container to quay.io/cloudnativetoolkit/terraform:v1.1

- scripts/oc-login.sh
> Updates message for login error

- main.tf
- scripts/oc-login.sh
> Sets kubeconfig properly before logging in

- main.tf
> Updates clis submodule to 1.9.5

- .github/workflows/verify-pr.yaml
- .github/workflows/verify-workflow.yaml
- .github/workflows/verify.yaml
- .gitignore
- README.md
- main.tf
- outputs.tf
- scripts/ibmcloud-login.sh
- scripts/oc-login.sh
- test/stages/stage-cluster.tf
- test/stages/variables.tf
> Implements workaround for oc login issue on ROKS 4.9 and 4.10 clusters

- .github/scripts/validate-deploy.sh
- scripts/ibmcloud-login.sh
> Adds kubectl test

- scripts/oc-login.sh
Signed-off-by: Rich Ehrhardt <rich_ehrhardt@au1.ibm.com>
> Added serverURL output to oc-login.sh

- main.tf
- scripts/oc-login.sh
- variables.tf
> Adds support for passing the CA cert for login

- .github/workflows/verify-pr.yaml
- .github/workflows/verify-workflow.yaml
- .github/workflows/verify.yaml
- main.tf
- scripts/oc-login.sh
- test/stages/stage-cluster.tf
- test/stages/variables.tf
- variables.tf
> Adds logging for ca cert file

- .github/scripts/validate-deploy.sh
- .github/workflows/verify-workflow.yaml
- main.tf
- outputs.tf
- scripts/get-cluster-info.sh
- test/stages/stage-cluster.tf
- variables.tf
> Looks up ingress_subdomain, tls_secret_name, and cluster_version

- outputs.tf
- scripts/oc-login.sh
> Outputs username, password and token

- outputs.tf
> Adds ca_cert variable to the output

- outputs.tf
> Outputs ca cert as base54 encoded string

- scripts/ibmcloud-login.sh
> Updates IBM url parsing to fix region for private urls

- outputs.tf
- scripts/get-cluster-info.sh
- Replaces serverUrl in id with IBM cluster id or OpenShift id
- Adds ocp_id to output with OpenShift cluster id
> Updates id outputs

- .github/workflows/verify-pr.yaml
- .github/workflows/verify-workflow.yaml
- scripts/oc-login.sh
fixes default permissions on kubeconfig to fix issue raised by @timroster
> fix permission on kubeconfig
